spring:
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tutorial?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    redis:
      time-to-live: 3600s
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 5
        max-idle: 10
        max-wait: 10000
  activemq:
    broker-url: tcp://127.0.0.1:61616
  jms:
    pub-sub-domain: true #true表示发布、订阅模式；false表示点对点模式；默认是点对点模式
    
mybatis:
  type-aliases-package: com.hello.springboot.mapper
  configuration:
    map-underscore-to-camel-case: true
      
logging:
  file: target/app.log
  level:
    ROOT: INFO
    com.zuimeihui: TRACE
    
server:
  use-forward-headers: true
  tomcat:
    remote-ip-header: X-Real-IP
    protocol-header: X-Forwarded-Proto
    